- name: playbook for file manipulation
  hosts: all
  become: yes
  tasks:
  - name: hello file copy
    copy:
      content: "hello from Monday evening"
      dest: /tmp/monday3.txt
  - name: hello file copy
    copy:
      content: "hi there."
      dest: /tmp/monday4.txt
  - name: archive hh is created
    archive:
      path:
      - /tmp/monday3.txt
      - /tmp/monday4.txt
      dest: /tmp/hh2.zip
      format: zip